# Generated by Django 5.2.5 on 2025-09-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience_years",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
