# Generated by Django 5.2.5 on 2025-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_appointment_doctor_alter_appointment_patient_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
